spring:
  datasource:
    url: ${DB_URL} # default 없음 (dev 환경에선 무조건 환경변수)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration,classpath:db/seed # ← 시드까지 포함
  thymeleaf:
    cache: false

  jwt:
    cookie:
      secure: false # 로컬은 http://localhost. Secure=true면 브라우저가 쿠키 거부.
