spring:
  datasource:
    hikari:
      maximum-pool-size: 30 # DB 연결 통로 개수 100 -> 30 축소, 필요시 이후 상향 조정
      minimum-idle: 7      # 유휴 상태일 때 유지할 최소 연결 수
    url: jdbc:mysql://localhost:3307/course_registration?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/seed    # ← 시드까지 포함 (local 전용)
  thymeleaf:
    cache: false

server:
  tomcat:
    threads:
      max: 200            # 동시에 처리할 수 있는 최대 스레드 수 (기본값 200)
      min-spare: 20       # 최소한 유지할 스레드 수
    max-connections: 5000 # 동시에 연결 가능한 최대 커넥션 수
    accept-count: 1000     # 모든 스레드가 바쁠 때 대기할 수 있는 큐(대기열) 크기

logging:
  level:
    root: WARN
    com.ops.app: INFO